package com.ar.myfirstapp.obd2.saej1979;

/*"
 " Created by Arun Soman on 3/3/2017.
 "*/

import com.ar.myfirstapp.obd2.Command;

public class Mode1 extends Mode{


    public final static Command commands[] ={
        new Command("01","00","PIDs supported [01 - 20]", response),
            new Command("01" , "1" , "Monitor status since DTCs cleared. (Includes malfunction indicator lamp (MIL) status and number of DTCs.)", response) ,
            new Command("01" , "2" , "Freeze DTC", response) ,
            new Command("01" , "3" , "Fuel system status", response) ,
            new Command("01" , "4" , "Calculated engine load", response) ,
            new Command("01" , "5" , "Engine coolant temperature", response) ,
            new Command("01" , "6" , "Short term fuel trim—Bank 1", response) ,
            new Command("01" , "7" , "Long term fuel trim—Bank 1", response) ,
            new Command("01" , "8" , "Short term fuel trim—Bank 2", response) ,
            new Command("01" , "9" , "Long term fuel trim—Bank 2", response) ,
            new Command("01" , "0A" , "Fuel pressure (gauge pressure)", response) ,
            new Command("01" , "0B" , "Intake manifold absolute pressure", response) ,
            new Command("01" , "0C" , "Engine RPM", response) ,
            new Command("01" , "0D" , "Vehicle speed", response) ,
            new Command("01" , "0E" , "Timing advance", response) ,
    new Command("01" , "0F" , "Intake air temperature", response) ,
    new Command("01" , "10" , "MAF air flow rate", response) ,
    new Command("01" , "11" , "Throttle position", response) ,
    new Command("01" , "12" , "Commanded secondary air status", response) ,
    new Command("01" , "13" , "Oxygen sensors present (in 2 banks)", response) ,
    new Command("01" , "14" , "Oxygen Sensor 1 A: Voltage B: Short term fuel trim", response) ,
    new Command("01" , "15" , "Oxygen Sensor 2 A: Voltage B: Short term fuel trim", response) ,
    new Command("01" , "16" , "Oxygen Sensor 3 A: Voltage B: Short term fuel trim", response) ,
    new Command("01" , "17" , "Oxygen Sensor 4 A: Voltage B: Short term fuel trim", response) ,
    new Command("01" , "18" , "Oxygen Sensor 5 A: Voltage B: Short term fuel trim", response) ,
    new Command("01" , "19" , "Oxygen Sensor 6 A: Voltage B: Short term fuel trim", response) ,
    new Command("01" , "1A" , "Oxygen Sensor 7 A: Voltage B: Short term fuel trim", response) ,
    new Command("01" , "1B" , "Oxygen Sensor 8 A: Voltage B: Short term fuel trim", response) ,
    new Command("01" , "1C" , "OBD standards this vehicle conforms to", response) ,
    new Command("01" , "1D" , "Oxygen sensors present (in 4 banks)", response) ,
    new Command("01" , "1E" , "Auxiliary input status", response) ,
    new Command("01" , "1F" , "Run time since engine start", response) ,
    new Command("01" , "20" , "PIDs supported [21 - 40]", response) ,
    new Command("01" , "21" , "Distance traveled with malfunction indicator lamp (MIL) on", response) ,
    new Command("01" , "22" , "Fuel Rail Pressure (relative to manifold vacuum)", response) ,
    new Command("01" , "23" , "Fuel Rail Gauge Pressure (diesel, or gasoline direct injection)", response) ,
    new Command("01" , "24" , "Oxygen Sensor 1 AB: Fuel–Air Equivalence Ratio CD: Voltage", response) ,
    new Command("01" , "25" , "Oxygen Sensor 2 AB: Fuel–Air Equivalence Ratio CD: Voltage", response) ,
    new Command("01" , "26" , "Oxygen Sensor 3 AB: Fuel–Air Equivalence Ratio CD: Voltage", response) ,
    new Command("01" , "27" , "Oxygen Sensor 4 AB: Fuel–Air Equivalence Ratio CD: Voltage", response) ,
    new Command("01" , "28" , "Oxygen Sensor 5 AB: Fuel–Air Equivalence Ratio CD: Voltage", response) ,
    new Command("01" , "29" , "Oxygen Sensor 6 AB: Fuel–Air Equivalence Ratio CD: Voltage", response) ,
    new Command("01" , "2A" , "Oxygen Sensor 7 AB: Fuel–Air Equivalence Ratio CD: Voltage", response) ,
    new Command("01" , "2B" , "Oxygen Sensor 8 AB: Fuel–Air Equivalence Ratio CD: Voltage", response) ,
    new Command("01" , "2C" , "Commanded EGR", response) ,
    new Command("01" , "2D" , "EGR Error", response) ,
    new Command("01" , "2E" , "Commanded evaporative purge", response) ,
    new Command("01" , "2F" , "Fuel Tank Level Input", response) ,
    new Command("01" , "30" , "Warm-ups since codes cleared", response) ,
    new Command("01" , "31" , "Distance traveled since codes cleared", response) ,
    new Command("01" , "32" , "Evap. System Vapor Pressure", response) ,
    new Command("01" , "33" , "Absolute Barometric Pressure", response) ,
    new Command("01" , "34" , "Oxygen Sensor 1    AB: Fuel–Air Equivalence Ratio CD: Current", response) ,
    new Command("01" , "35" , "Oxygen Sensor 2 AB: Fuel–Air Equivalence Ratio CD: Current", response) ,
    new Command("01" , "36" , "Oxygen Sensor 3 AB: Fuel–Air Equivalence Ratio CD: Current", response) ,
    new Command("01" , "37" , "Oxygen Sensor 4 AB: Fuel–Air Equivalence Ratio CD: Current", response) ,
    new Command("01" , "38" , "Oxygen Sensor 5 AB: Fuel–Air Equivalence Ratio CD: Current", response) ,
    new Command("01" , "39" , "Oxygen Sensor 6 AB: Fuel–Air Equivalence Ratio CD: Current", response) ,
    new Command("01" , "3A" , "Oxygen Sensor 7 AB: Fuel–Air Equivalence Ratio CD: Current", response) ,
    new Command("01" , "3B" , "Oxygen Sensor 8 AB: Fuel–Air Equivalence Ratio CD: Current", response) ,
    new Command("01" , "3C" , "Catalyst Temperature: Bank 1, Sensor 1", response) ,
    new Command("01" , "3D" , "Catalyst Temperature: Bank 2, Sensor 1", response) ,
    new Command("01" , "3E" , "Catalyst Temperature: Bank 1, Sensor 2", response) ,
    new Command("01" , "3F" , "Catalyst Temperature: Bank 2, Sensor 2", response) ,
    new Command("01" , "40" , "PIDs supported [41 - 60]", response) ,
    new Command("01" , "41" , "Monitor status this drive cycle", response) ,
    new Command("01" , "42" , "Control module voltage", response) ,
    new Command("01" , "43" , "Absolute load value", response) ,
    new Command("01" , "44" , "Fuel–Air commanded equivalence ratio", response) ,
    new Command("01" , "45" , "Relative throttle position", response) ,
    new Command("01" , "46" , "Ambient air temperature", response) ,
    new Command("01" , "47" , "Absolute throttle position B", response) ,
    new Command("01" , "48" , "Absolute throttle position C", response) ,
    new Command("01" , "49" , "Accelerator pedal position D", response) ,
    new Command("01" , "4A" , "Accelerator pedal position E", response) ,
    new Command("01" , "4B" , "Accelerator pedal position F", response) ,
    new Command("01" , "4C" , "Commanded throttle actuator", response) ,
    new Command("01" , "4D" , "Time run with MIL on", response) ,
    new Command("01" , "4E" , "Time since trouble codes cleared", response) ,
    new Command("01" , "4F" , "Maximum value for Fuel–Air equivalence ratio, oxygen sensor voltage, oxygen sensor current, and intake manifold absolute pressure", response) ,
    new Command("01" , "50" , "Maximum value for air flow rate from mass air flow sensor", response) ,
    new Command("01" , "51" , "Fuel Type", response) ,
    new Command("01" , "52" , "Ethanol fuel %", response) ,
    new Command("01" , "53" , "Absolute Evap system Vapor Pressure", response) ,
    new Command("01" , "54" , "Evap system vapor pressure", response) ,
    new Command("01" , "55" , "Short term secondary oxygen sensor trim, A: bank 1, B: bank 3", response) ,
    new Command("01" , "56" , "Long term secondary oxygen sensor trim, A: bank 1, B: bank 3", response) ,
    new Command("01" , "57" , "Short term secondary oxygen sensor trim, A: bank 2, B: bank 4", response) ,
    new Command("01" , "58" , "Long term secondary oxygen sensor trim, A: bank 2, B: bank 4", response) ,
    new Command("01" , "59" , "Fuel rail absolute pressure", response) ,
    new Command("01" , "5A" , "Relative accelerator pedal position", response) ,
    new Command("01" , "5B" , "Hybrid battery pack remaining life", response) ,
    new Command("01" , "5C" , "Engine oil temperature", response) ,
    new Command("01" , "5D" , "Fuel injection timing", response) ,
    new Command("01" , "5E" , "Engine fuel rate", response) ,
    new Command("01" , "5F" , "Emission requirements to which vehicle is designed", response) ,
    new Command("01" , "60" , "PIDs supported [61 - 80]", response) ,
    new Command("01" , "61" , "Driver's demand engine - percent torque", response) ,
    new Command("01" , "62" , "Actual engine - percent torque", response) ,
    new Command("01" , "63" , "Engine reference torque", response) ,
    new Command("01" , "64" , "Engine percent torque data", response) ,
    new Command("01" , "65" , "Auxiliary input / output supported", response) ,
    new Command("01" , "66" , "Mass air flow sensor", response) ,
    new Command("01" , "67" , "Engine coolant temperature", response) ,
    new Command("01" , "68" , "Intake air temperature sensor", response) ,
    new Command("01" , "69" , "Commanded EGR and EGR Error", response) ,
    new Command("01" , "6A" , "Commanded Diesel intake air flow control and relative intake air flow position", response) ,
    new Command("01" , "6B" , "Exhaust gas recirculation temperature", response) ,
    new Command("01" , "6C" , "Commanded throttle actuator control and relative throttle position", response) ,
    new Command("01" , "6D" , "Fuel pressure control system", response) ,
    new Command("01" , "6E" , "Injection pressure control system", response) ,
    new Command("01" , "6F" , "Turbocharger compressor inlet pressure", response) ,
    new Command("01" , "70" , "Boost pressure control", response) ,
    new Command("01" , "71" , "Variable Geometry turbo (VGT) control", response) ,
    new Command("01" , "72" , "Wastegate control", response) ,
    new Command("01" , "73" , "Exhaust pressure", response) ,
    new Command("01" , "74" , "Turbocharger RPM", response) ,
    new Command("01" , "75" , "Turbocharger temperature", response) ,
    new Command("01" , "76" , "Turbocharger temperature", response) ,
    new Command("01" , "77" , "Charge air cooler temperature (CACT)", response) ,
    new Command("01" , "78" , "Exhaust Gas temperature (EGT) Bank 1", response) ,
    new Command("01" , "79" , "Exhaust Gas temperature (EGT) Bank 2", response) ,
    new Command("01" , "7A" , "Diesel particulate filter (DPF)", response) ,
    new Command("01" , "7B" , "Diesel particulate filter (DPF)", response) ,
    new Command("01" , "7C" , "Diesel Particulate filter (DPF) temperature", response) ,
    new Command("01" , "7D" , "NOx NTE (Not-To-Exceed) control area status", response) ,
    new Command("01" , "7E" , "PM NTE (Not-To-Exceed) control area status", response) ,
    new Command("01" , "7F" , "Engine run time", response) ,
    new Command("01" , "80" , "PIDs supported [81 - A0]", response) ,
    new Command("01" , "81" , "Engine run time for Auxiliary Emissions Control Device(AECD)", response) ,
    new Command("01" , "82" , "Engine run time for Auxiliary Emissions Control Device(AECD)", response) ,
    new Command("01" , "83" , "NOx sensor", response) ,
    new Command("01" , "84" , "Manifold surface temperature", response) ,
    new Command("01" , "85" , "NOx reagent system", response) ,
    new Command("01" , "86" , "Particulate matter (PM) sensor", response) ,
    new Command("01" , "87" , "Intake manifold absolute pressure", response) ,
    new Command("01" , "A0" , "PIDs supported [A1 - C0]", response) ,
    new Command("01" , "C0" , "PIDs supported [C1 - E0]", response) ,
    new Command("01" , "C3" , "?", response) ,
    new Command("01" , "C4" , "?", response)
};

    public Mode1() {
        super("1");
    }

    protected Mode1(String id){
        super(id);
    }

    @Override
    protected Command getCommand(int index) {
        return commands[index];
    }
}
